//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiPractica4.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PracticaS12Entities : DbContext
    {
        public PracticaS12Entities()
            : base("name=PracticaS12Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Abonos> Abonos { get; set; }
        public virtual DbSet<Principal> Principal { get; set; }
    
        public virtual int RegistrarAbonoSP(Nullable<long> idCompra, Nullable<decimal> monto)
        {
            var idCompraParameter = idCompra.HasValue ?
                new ObjectParameter("IdCompra", idCompra) :
                new ObjectParameter("IdCompra", typeof(long));
    
            var montoParameter = monto.HasValue ?
                new ObjectParameter("Monto", monto) :
                new ObjectParameter("Monto", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RegistrarAbonoSP", idCompraParameter, montoParameter);
        }
    
        public virtual ObjectResult<SP_ConsultarProducto_Result> SP_ConsultarProducto(Nullable<int> id_Compra)
        {
            var id_CompraParameter = id_Compra.HasValue ?
                new ObjectParameter("Id_Compra", id_Compra) :
                new ObjectParameter("Id_Compra", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ConsultarProducto_Result>("SP_ConsultarProducto", id_CompraParameter);
        }
    
        public virtual ObjectResult<SP_ORDENADO_Result> SP_ORDENADO()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ORDENADO_Result>("SP_ORDENADO");
        }
    
        public virtual ObjectResult<SP_ProductosPendientes_Result> SP_ProductosPendientes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ProductosPendientes_Result>("SP_ProductosPendientes");
        }
    }
}
